# frozen_string_literal: true

require_relative "rule"

# Requiring a rule file registers the rule, so this list is the only place a
# new rule has to be mentioned. Sorted by name to make an addition a one-line
# diff rather than an argument about ordering.
require_relative "rules/addomit_without_scanfrom"
require_relative "rules/advance_warning_body"
require_relative "rules/banner_placement"
require_relative "rules/calendar_text_limited"
require_relative "rules/callback_signature"
require_relative "rules/clause_needs_full_date"
require_relative "rules/clause_requires_at"
require_relative "rules/clause_value_range"
require_relative "rules/color_component_range"
require_relative "rules/coordinate_not_string"
require_relative "rules/dangling_continuation"
require_relative "rules/date_out_of_range"
require_relative "rules/debug_command"
require_relative "rules/easterdate_from_today"
require_relative "rules/function_arity"
require_relative "rules/function_redefinition"
require_relative "rules/iftrig_with_satisfy"
require_relative "rules/include_path"
require_relative "rules/info_clause"
require_relative "rules/info_substitution_without_header"
require_relative "rules/keyword_case"
require_relative "rules/license_header"
require_relative "rules/line_length"
require_relative "rules/literal_type_mismatch"
require_relative "rules/omit_aware_delta"
require_relative "rules/push_vars_missing_name"
require_relative "rules/repeat_trigger"
require_relative "rules/satisfy_constraint"
require_relative "rules/shell_maxlen"
require_relative "rules/shell_use_while_run_disabled"
require_relative "rules/string_escape"
require_relative "rules/syntax"
require_relative "rules/system_variable_assignment"
require_relative "rules/tag_syntax"
require_relative "rules/text_after_eof_marker"
require_relative "rules/time_zone_name"
require_relative "rules/todo_complete_through"
require_relative "rules/trailing_whitespace"
require_relative "rules/translate_command"
require_relative "rules/unbalanced_blocks"
require_relative "rules/unbalanced_delimiters"
require_relative "rules/unknown_special_type"
require_relative "rules/unknown_substitution_sequence"
require_relative "rules/unknown_system_variable"
require_relative "rules/unquoted_shell_substitution"
require_relative "rules/until_before_from"
require_relative "rules/world_writable_script"
