# frozen_string_literal: true

require_relative "../rule"

module RemLint
  module Rules
    # Hand-written commands in a file a tool owns.
    #
    # TkRemind appends to its own file; `ics2rem` and `radicale-remind`
    # regenerate theirs from the other side of a sync. A command written into
    # one of those by hand survives until the next write and then does not, and
    # in the meantime the file mixes authored and generated state in something
    # no human is expected to read.
    #
    # Which files a tool owns is not something the linter can work out, so it is
    # configured -- `GeneratedFiles` takes shell globs. With none configured the
    # rule has nothing to say, which is the honest default rather than a guess
    # about anybody's layout.
    #
    # Comments are not reported: a note at the top of a generated file is how
    # people mark it as generated in the first place.
    class GeneratedFileEdited < Rule
      # What the tools write, and so what is *not* a hand edit. TkRemind tags
      # everything it appends.
      GENERATED_TAG = /\bTAG\s+"?TKTAG\d+/i

      def self.default_severity
        "warning"
      end

      def self.description
        "Hand-written commands in a file listed under GeneratedFiles."
      end

      def check
        patterns = option("GeneratedFiles", [])

        if !patterns.empty? && generated?(patterns)
          report
        end
      end

      private

        def generated?(patterns)
          patterns.any? do |pattern|
            File.fnmatch?(pattern, document.path.to_s, File::FNM_PATHNAME | File::FNM_EXTGLOB)
          end
        end

        def report
          hand_written.each do |command|
            offend(
              command.line,
              "this file is generated, and a hand-written command in it survives only " \
              "until the tool next writes the file",
              column: command.keyword_column,
            )
          end
        end

        # Anything the tool did not put there itself.
        def hand_written
          document.code_commands.reject { |command| command.text.match?(GENERATED_TAG) }
        end
    end
  end
end

__END__

require_relative "../document"

describe "RemLint::Rules::GeneratedFileEdited" do
  lint = proc do |text, path = "calendar.rem", config = {}|
    source = RemLint::Source.new(path: path, text: text)

    RemLint::Rules::GeneratedFileEdited.new(config).run(RemLint::Document.new(source))
  end

  owned = { "GeneratedFiles" => ["*.generated.rem", "tkremind/*.rem"] }

  it "says nothing when no files are declared generated" do
    lint.("REM 1 Jan MSG hi\n").should.be.empty
  end

  it "says nothing about a file outside the patterns" do
    lint.("REM 1 Jan MSG hi\n", "mine.rem", owned).should.be.empty
  end

  it "reports a hand-written command in a generated file" do
    offenses = lint.("REM 1 Jan MSG hi\n", "notes.generated.rem", owned)

    offenses.length.should == 1
    offenses.first.message.should.match(/survives only until the tool next writes the file/)
  end

  it "matches a pattern with a directory" do
    lint.("REM 1 Jan MSG hi\n", "tkremind/appts.rem", owned).length.should == 1
  end

  it "does not report what TkRemind wrote itself" do
    text = %(REM 1 Jan TAG "TKTAG1" MSG Appointment\n)

    lint.(text, "tkremind/appts.rem", owned).should.be.empty
  end

  it "reports only the hand-written commands among generated ones" do
    text = %(REM 1 Jan TAG "TKTAG1" MSG Generated\nREM 2 Jan MSG By hand\n)

    lint.(text, "tkremind/appts.rem", owned).map(&:line).should == [2]
  end

  it "says nothing about comments, which is how files are marked generated" do
    lint.("# Generated by TkRemind -- do not edit\n", "tkremind/a.rem", owned).should.be.empty
  end

  it "points at the keyword" do
    lint.("   REM 1 Jan MSG hi\n", "a.generated.rem", owned).first.column.should == 4
  end

  it "reports at warning severity" do
    lint.("REM 1 Jan MSG hi\n", "a.generated.rem", owned).first.severity.should == "warning"
  end
end
