# frozen_string_literal: true

require "fileutils"

require_relative "library"

module Remind
  # Builds Remind's sources, plus this gem's shim, into a shared library.
  #
  # Remind's own Makefile links two programs and no library, so this is the
  # one step that has to be invented rather than reused. It is deliberately
  # thin: `./configure` still decides the compiler, the flags, the feature
  # macros and the libraries to link, and this class reads those decisions
  # back out of the generated `src/Makefile` rather than making its own. What
  # it adds is `-fPIC -shared`, one output file, and `ext/shim.c`.
  #
  # The output goes where `Remind::Library` looks -- lib/remind/ -- because
  # that is where a precompiled gem carries it, and a checkout that puts it
  # somewhere else is a checkout that tests a different arrangement than the
  # one users get.
  #
  # `rem2ps.c` is left out: the PostScript formatter is a second program with
  # a second `main`, and nothing in it is worth binding. `main.c` stays in --
  # a `main` symbol in a shared library is harmless, and leaving it out would
  # strand every symbol defined beside it.
  class Builder
    EXCLUDED_SOURCES = ["rem2ps.c"].freeze

    SHARED_FLAGS = ["-fPIC", "-shared"].freeze

    # Remind resolves `INCLUDE` against this at runtime; pointing it at the
    # vendored tree means a reminder can include the holiday files that ship
    # with the release the bindings bind.
    SYSDIR_TEMPLATE = "-DSYSDIR=%s"

    # Extra arguments for `./configure`.
    #
    # There is one job that needs them: building a library to put inside a
    # precompiled gem. Remind's configure links readline when it finds it, and
    # a gem whose library needs a readline the installing machine may not have
    # is a gem that fails to load there. CI therefore builds with
    #
    #   REMIND_RB_CONFIGURE_ARGS="ac_cv_lib_readline_readline=no
    #                             ac_cv_header_readline_readline_h=no"
    #
    # which tells configure's own cache the probe already failed. Nothing in
    # the bindings uses readline -- it is there for `remind`'s interactive
    # prompt, and there is no prompt in a library.
    CONFIGURE_ARGS = "REMIND_RB_CONFIGURE_ARGS"

    attr_reader :source_root, :output, :io

    def initialize(source_root: Library.source_root, output: Library.default_path, io: $stderr)
      @source_root = source_root
      @output = output
      @io = io
    end

    # Answers the path it built.
    def call
      configure
      generate_translatables
      compile

      output
    end

    private

      def source_directory
        File.join(source_root, "src")
      end

      def makefile
        File.join(source_directory, "Makefile")
      end

      # `configure` writes src/Makefile, src/config.h and src/version.h. It is
      # slow and idempotent, so it runs once and not again unless its output
      # has gone.
      def configure
        if File.exist?(makefile)
          io.puts("configure: already done")
        else
          run(configure_command, chdir: source_root, what: "configure")
        end
      end

      def configure_command
        ["./configure", ENV.fetch(CONFIGURE_ARGS, nil)].compact.join(" ")
      end

      # xlat.c is generated by a Makefile rule that greps every `tr()` string
      # out of the sources. Nothing else defines `translatables`, so a library
      # built without it fails to load rather than failing to build.
      def generate_translatables
        run("make xlat.c", chdir: source_directory, what: "make xlat.c")
      end

      def compile
        FileUtils.mkdir_p(File.dirname(output))
        run(compile_command, chdir: source_directory, what: "compile")
      end

      def compile_command
        [
          compiler,
          *compile_flags,
          *SHARED_FLAGS,
          format(SYSDIR_TEMPLATE, File.join(source_root, "include")),
          "-o",
          output,
          *sources,
          *link_libraries,
        ].join(" ")
      end

      # The shim is compiled from where it lives rather than copied in beside
      # the Remind sources, so a build leaves nothing behind in the vendored
      # tree.
      def sources
        remind_sources + [Library.shim]
      end

      def remind_sources
        Dir.children(source_directory)
           .select { |name| name.end_with?(".c") }
           .reject { |name| EXCLUDED_SOURCES.include?(name) }
           .sort
      end

      # --- what configure decided ------------------------------------------

      def makefile_text
        File.read(makefile)
      end

      # The recipe under the `.c.o` suffix rule: the exact command configure
      # chose for compiling one source file.
      def compile_recipe
        recipe(/^\.c\.o:\n\t(.*)$/)
      end

      # The recipe that links the program, which is where the libraries are.
      def link_recipe
        recipe(/^remind: [^\n]*\n\t(.*)$/)
      end

      def recipe(pattern)
        match = makefile_text.match(pattern)

        if match
          match[1].split
        else
          raise BuildError, "#{makefile} has no recipe matching #{pattern.inspect}"
        end
      end

      def compiler
        compile_recipe.first
      end

      # Everything the compile recipe passes except the parts that are about
      # compiling one file into one object: `-c`, the source, and the make
      # variables, which have no values outside make.
      def compile_flags
        compile_recipe.drop(1).reject { |flag| skip_flag?(flag) }
      end

      def skip_flag?(flag)
        flag == "-c" || flag.include?("$") || flag.start_with?("-DSYSDIR")
      end

      def link_libraries
        link_recipe.select { |flag| flag.start_with?("-l") }
      end

      def run(command, chdir:, what:)
        io.puts("#{what}: #{command}")

        if system(command, chdir: chdir)
          command
        else
          raise BuildError, "#{what} failed in #{chdir}: #{command}"
        end
      end
  end
end

__END__

require "stringio"

describe "Remind::Builder" do
  # The build itself is what `rake library` does, and what every other spec
  # here depends on having run. What is worth pinning is that the build takes
  # its decisions from configure's output rather than inventing them.
  builder = proc { Remind::Builder.new(io: StringIO.new) }

  it "builds from the vendored sources" do
    builder.().send(:source_directory).should == Remind::Library.source_directory
  end

  it "leaves the PostScript formatter out, and keeps main.c in" do
    Remind::Builder::EXCLUDED_SOURCES.should.include "rem2ps.c"
    Remind::Builder::EXCLUDED_SOURCES.should.not.include "main.c"
  end

  it "compiles the shim alongside them" do
    builder.().send(:sources).last.should == Remind::Library.shim
  end

  it "takes the compiler from the generated Makefile" do
    builder.().send(:compiler).should.not.be.empty
  end

  it "drops the flags that only make sense one file at a time" do
    flags = builder.().send(:compile_flags)

    flags.should.not.include "-c"
    flags.any? { |flag| flag.include?("$") }.should.be.false
  end

  it "keeps the feature macros configure defined" do
    builder.().send(:compile_flags).should.include "-DHAVE_CONFIG_H"
  end

  it "links what the program links" do
    builder.().send(:link_libraries).all? { |flag| flag.start_with?("-l") }.should.be.true
  end

  it "passes on the configure arguments packaging needs" do
    ENV[Remind::Builder::CONFIGURE_ARGS] = "ac_cv_lib_readline_readline=no"

    builder.().send(:configure_command).should == "./configure ac_cv_lib_readline_readline=no"
  ensure
    ENV.delete(Remind::Builder::CONFIGURE_ARGS)
  end

  it "configures with nothing extra by default" do
    builder.().send(:configure_command).should == "./configure"
  end

  it "builds one shared library out of all of it" do
    command = builder.().send(:compile_command)

    command.should.include "-fPIC"
    command.should.include "-shared"
    command.should.include "expr.c"
    command.should.not.include "rem2ps.c"
  end
end
